app1/urls.py
from django.urls import path
from app1.views import *
app_name='connect'

urlpatterns=[
path('html1/',html1,name='html1'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='connect1'

urlpatterns=[
  path('html2/',html2,name='html2'),
]

specifurl/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def html1(request):
  return render(request,'html1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def html2(request):
  return render(request,'html2.html')

templates/html1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <center>
    <h1>Specific url  of app1</h1>
    <a href="{% url 'connect1:html2' %}">RESPONSE TO HTML2</a>
  </center>
</body>
</html>

templates/html2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <center>
    <h1>Specifc url navigation of app2</h1>
    <a href="{% url 'connect:html1' %}">RESPONSE TO HTML1</a>

  </center>
  
</body>
</html>